[package]
name = "camgrid"
version = "0.1.0"
authors = ["Francis Lavoie <lavofr@gmail.com>"]
edition = "2018"

[dependencies]
conrod = { version = "0.61.1", features = ["glium", "winit"] }
find_folder = "0.3.0"
notify = "4.0.6"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"